#!/bin/bash

####################################################                    .....(JJJJJ.....
####################################################              ..gMMMMMMMMMMMMMMMMMMMMMMN+,.
####                                            ####          .(MMMMM""^`               ''""MMMMNa,
####       ########   #######   #########       ####        .MMM#"`                           7HMMMa.
####     ########   #######   #########         ####      .MMM"                                  7MMMe
####                        #########           ####     dMMMMMMMNg(....                .....)gMMMMMMMN.
####                      #########             ####    JMM^ _7""HMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""! ,MMb
####                    #########               ####    MM#          dM#?7""""""""""""7?MMN          dMM
####                  #########   ###     ###   ####    MMN.        .MMF                (MM|         MM#
####                #########    ###     ###    ####    ,MMN,      .MM#                  MMN,      .MMM^
####              #########     ###     ###     ####      TMMNJ.  .MMM!                  .MMN,  ..MMMB`
####            #########      ####   #####     ####       .TMMMMMMMN..                  ..MMMMMMMMD!
####          #########         #######  ##     ####           ?TWMMMMMMMMMMMNNNNNMMMMMMMMMMMMY"^
####        #########                           ####                   ?7"""""""""""""""7!
####      ###################################   ####
####   ####################################     ####    Zu : A shell script for students who take notes with PC.
####                                            ####    HIBIKI CUBE : @hibiki_cube, hibiki.apple.1984+dev@gmail.com
####################################################    MIT LISENCE
####################################################

ver="Zu 0.0.0"
desc="Easy pictuer operator"

# config
if [[ -e ~/.config/zu/config ]]; then
    . ~/.config/zu/config
else
    mkdir ~/.config/zu
    cat << EOS > ~/.config/zu/config
# default settings
location=./
color=#363b40
size=500x500
name=zu
format=png
EOS
    . ~/.config/zu/config
fi

zero () {
    cat <<EOS
$ver $desc
Got 0 argument. Generate picture by default settings.
EOS
    if [[ -e "$location$name.$format" ]]; then
        local num=2
        while [[ -e "$location$name$num.$format" ]]
        do
            num=$((++num))
        done
        magick convert -size $size xc:$color "$location$name$num.$format"
    else
        magick convert -size $size xc:$color "$location$name.$format"
    fi
}

one () {
    cat <<EOS
$ver $desc
Got 1 arguments.
EOS
}

two () {
    cat <<EOS
$ver $desc
Got 2 arguments.
EOS
}

three () {
    cat <<EOS
$ver $desc
Got 3 arguments.
EOS
}

four () {
    cat <<EOS
$ver $desc
Got 4 arguments.
EOS
}



case $# in
    0 ) zero ;;
    1 ) one ;;
    2 ) two ;;
    3 ) three ;;
    4 ) four ;;
esac